server:
  port: 8000
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
grpc:
  server:
    port: 8010
  client:
    GLOBAL:
      negotiation-type: plaintext
